services:
  - type: web
    name: my-strapi-backend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi-postgres
    databaseName: strapi
    user: strapi